### ISSUE TITLE
Consider using version 5.0 of the SymSpell algorithm

### ISSUE THREAD

**Issue by wolfgarbe** [searchhub/preDict#1]
Please consider updating preDict to use version 5.0 of the SymSpell algorithm (instead of version 3.0).
v5.0 fixes some bugs which prevented the suggestion to be complete under some circumstances. 
A new prefix indexing method also significantly reduces the memory consumption.
See https://github.com/wolfgarbe/symspell#changes-in-v50 for details.

**Comment by searchhub** [comment]
Thx for creating the issue. We already experienced the issue of incomplete candidate lists and we put it on our preDict roadmap.

**Comment by searchhub** [comment]
now after we have heavily tested if it would make sense to update our repo to a newer version of symspell we came to the conclusion that we won't update. The downside in speed and accuracy and code-complexity is not worth it - at least for us and our use cases
