### ISSUE TITLE
Undefined methods in the PreDictSettings class

### ISSUE THREAD

**Issue by ryac** [searchhub/preDict#2]
Hello,

I'm getting errors related to undefined methods in the PreDictSettings class (eg: getEditDistanceMax, getAccuracyLevel, getReplaceWeight, setEditDistanceMax, setAccuracyLevel, etc.)

Am I missing something?

**Comment by rudibatt** [comment]
Hi, 
we are using [lombok](https://projectlombok.org/) to generate getters (and setters and other boilerplate code). A maven build should work automatically, however you would need to install some lombok extension to get according IDE support. Checkout the [lombok website](https://projectlombok.org/) for more information.
Let me know, if this helped or if you need further help. Maybe some more details (stacktraces, etc) would be helpful.

**Comment by ryac** [comment]
Thank you for this! That's what it was. The maven builds were compiling fine, and once I added the lombok jar to the project the errors in my IDE were gone.
