### ISSUE TITLE
Do you have tutorial or API documentation ?

### ISSUE THREAD

**Issue by ttpro1995** [searchhub/preDict#4]
I would like apply preDict to my project. 
I need documentation.

**Comment by rudibatt** [comment]
Hi @ttpro1995 , I just added [a wiki page with some basic usage introduction for PreDict](https://github.com/searchhub/preDict/wiki). I hope this helps. Please let me know about further questions or if need more specific information.

**Comment by ttpro1995** [comment]
**// init**

        wordSearch = PreDictFactory.getCommunityEdition(AccuracyLevel.maximum);

**// load data**

        try (Stream<String> stream = Files.lines(Paths.get(dictDir))) {
            // stream.forEach(System.out::println);
            stream.flatMap(x -> Arrays.stream(x.split("\\s+"))).map(x -> wordSearch.indexWord(x)).count();

        } catch (IOException e) {
            e.printStackTrace();
        }

**// run** 

        List<String> result = wordSearch.findSimilarWords(text);

I can manage to get it work. However, I think I need description (also example if possible) about thing in [Setting](https://github.com/searchhub/preDict/blob/f3f0cac0fb28c4454038666ef93ef7f4472acf36/pre-dict-library/src/main/java/de/cxp/predict/api/PreDictSettings.java) like what each setting do, possible value, etc ...

**Comment by ttpro1995** [comment]
After I create CommunityCustomization

        PreDictSettings a = new PreDictSettings();
        a.setEditDistanceMax(2);
        a.setAccuracyLevel(PreDict.AccuracyLevel.maximum);
        a.setTopK(10);
        
        CommunityCustomization ce = new CommunityCustomization(a);

How can I load dictionary, and run findSimilarWords  (like object WordSearch )

**Comment by rudibatt** [comment]
At the wiki page I explained the single Settings options: https://github.com/searchhub/preDict/wiki#options
with #5 I also added a full example
