### ISSUE TITLE
How to load dictionary (training data) and search from input token with CommunityCustomization

### ISSUE THREAD

**Issue by ttpro1995** [searchhub/preDict#5]
After I create CommunityCustomization

        PreDictSettings a = new PreDictSettings();
        a.setEditDistanceMax(2);
        a.setAccuracyLevel(PreDict.AccuracyLevel.maximum);
        a.setTopK(10);
        
        CommunityCustomization ce = new CommunityCustomization(a);

How can I load dictionary, and run findSimilarWords  (like object WordSearch )

(need example, or getting started tutorial)

**Comment by rudibatt** [comment]
```
// ...
PreDict dictIndex = new PreDict(ce);
// read the data you want to search: for each word do
dictIndex.indexWord(word);

// then you can search on it:
String queryWord = "wort";
List<String> foundWords = dictIndex.findSimilarWords(queryWord);
System.out.println("found words: "+foundWords);
```

I also added this combined example at the wiki page.
Better?
